<?php

namespace app\admin\controller;

use app\common\model\Category;
use think\Controller;

class Article extends Controller
{
    protected $db;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Article();
    }

    //文章列表
    public function index(){
        $arcList = $this->db->getAll();
        $this->assign('arcList',$arcList);
        return $this->fetch();
    }
    /*
     * 添加文章
     */
    public function store(){
        //把psot请求数据交由模型处理
        if(request()->isPost()){
            $res = $this->db->store(input('post.'));

            if($res['valid']){
                //添加成功
                $this->success($res['msg'],'index');exit;
            }else{
                //添加失败
                $this->error($res['msg']);exit;
            }
        }
        //1.获取所有分类数据
        $cateData = (new Category())->getAllCate();
        $this->assign('cateData',$cateData);
        //2.获取所有标签
        $tagList = db('tag')->select();
        $this->assign('tagList',$tagList);
        return $this->fetch();
    }
    /**
     * 更新排序
     */
    public function upSort(){
        if(request()->isAjax()){
            $res = $this->db->upSort(input('post.'));
            if($res['valid']){
                //修改成功
               $this->success($res['msg'],'index');exit;
            }else{
                //修改失败
                $this->error($res['msg']);exit;
            }
        }
    }
}
