<?php

namespace app\admin\controller;

use think\Controller;

class Link extends Controller
{
    protected $db;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Link();
    }
    //友情链接首页
    public function index(){
        $linkList = db('link')->paginate(2);
        $this->assign('links',$linkList);
        return $this->fetch();
    }
    //添加友链
    public function store(){
        if(request()->isPost()){
//           halt(input('post.'));
            $res = $this->db->add(input('post.'));

            if($res['valid']){
                //执行成功
                $this->success($res['msg'],'admin/Link/index');exit;
            }else{
                //执行失败
                $this->error($res['msg']);exit;
            }
        }
        return $this->fetch();
    }
}
