<?php

namespace app\admin\controller;

use think\Controller;

class Tag extends Controller
{
    protected $db;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Tag();
    }

    //标签列表渲染
    public function index(){
        //获取标签列表数据
        $tagList = db('tag')->paginate(3);
        //分配数据给模板
        $this->assign('tagList',$tagList);

        return $this->fetch();
    }
    /**
     * 添加标签
     */
    public function store(){

        if(request()->isPost()) {
            $res = $this->db->store(input('post.'));

            if ($res['valid']) {
                //添加成功
                $this->success($res['msg'], 'admin/Tag/index');
                exit;
            } else {
                //添加失败
                $this->error($res['msg']);
                exit;
            }
        }
        return $this->fetch('store');
    }
    /*
     * 编辑标签
     */
    public function edit(){
        //获取地址栏传来的id
        $tag_id = input('param.tag_id');
        //获取旧数据
        $oldData = db('tag')->where('tag_id',$tag_id)->find();
        $this->assign('oldData',$oldData);
        //判断post请求
        if(request()->isPost()){
            //交给模型处理
            $res =$this->db->edit($tag_id,input('post.'));

            if($res['valid']){
                //修改成功
                $this->success($res['msg'],'admin/Tag/index');exit;
            }else{
                //修改失败
                $this->error($res['msg']);exit;
            }
        }
        return $this->fetch();
    }
    /*
     * 删除标签
    */
    public function del(){
        $tag_id = input('get.tag_id');
        if(db('tag')->where('tag_id',$tag_id)->delete()){
            //删除成功
            $this->success('删除成功','admin/Tag/index');exit;
        }else{
            //删除失败
            $this->error('删除失败');exit;
        }
    }
}
